export interface MenuItem {
    id: string;
    name: string;
    description: string;
    category: string;
    price: number;
    image: string;
    isVeg: boolean;
    spiceLevel?: 1 | 2 | 3; // 1 = Mild, 2 = Medium, 3 = Spicy
    available: boolean;
}

export const menuData: MenuItem[] = [
    // STARTERS (10 items)
    {
        id: 'st-001',
        name: 'Chicken Mutthi Kabab',
        description: 'Spicy minced chicken kababs with authentic Saoji spices',
        category: 'Starters',
        price: 280,
        image: '/starters.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'st-002',
        name: 'Chicken Roast – Saoji Style',
        description: 'Tender chicken pieces roasted with traditional Saoji masala',
        category: 'Starters',
        price: 320,
        image: '/starters.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'st-003',
        name: 'Coconut Mutthi Kabab',
        description: 'Unique kababs with coconut and aromatic spices',
        category: 'Starters',
        price: 260,
        image: '/starters.png',
        isVeg: true,
        spiceLevel: 2,
        available: true,
    },
    {
        id: 'st-004',
        name: 'Fried Chicken – Saoji Style',
        description: 'Crispy fried chicken with fiery Saoji spices',
        category: 'Starters',
        price: 300,
        image: '/starters.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'st-005',
        name: 'Garam Boti',
        description: 'Hot and spicy mutton pieces, a Saoji specialty',
        category: 'Starters',
        price: 350,
        image: '/starters.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'st-006',
        name: 'Hariyo Chicken Fry',
        description: 'Green chicken fry with fresh herbs and spices',
        category: 'Starters',
        price: 290,
        image: '/starters.png',
        isVeg: false,
        spiceLevel: 2,
        available: true,
    },
    {
        id: 'st-007',
        name: 'Liver Fry – Saoji Style',
        description: 'Spicy liver fry cooked to perfection',
        category: 'Starters',
        price: 270,
        image: '/starters.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'st-008',
        name: 'Mint Mushroom Fry',
        description: 'Fresh mushrooms with mint and aromatic spices',
        category: 'Starters',
        price: 240,
        image: '/starters.png',
        isVeg: true,
        spiceLevel: 2,
        available: true,
    },
    {
        id: 'st-009',
        name: 'Mutton Chops – Saoji Style',
        description: 'Tender mutton chops marinated in Saoji spices',
        category: 'Starters',
        price: 380,
        image: '/starters.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'st-010',
        name: 'Mutton Mutthi Kabab',
        description: 'Spicy minced mutton kababs, a true delicacy',
        category: 'Starters',
        price: 340,
        image: '/starters.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },

    // MAIN COURSE (9 items)
    {
        id: 'mc-001',
        name: 'Chukka Kura Mutton',
        description: 'Mutton cooked with sorrel leaves in traditional style',
        category: 'Main Course',
        price: 420,
        image: '/hero-food.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'mc-002',
        name: 'Dal Tadka',
        description: 'Yellow lentils tempered with aromatic spices',
        category: 'Main Course',
        price: 180,
        image: '/hero-food.png',
        isVeg: true,
        spiceLevel: 1,
        available: true,
    },
    {
        id: 'mc-003',
        name: 'Keema Ko Wangi',
        description: 'Minced meat with eggplant in Saoji gravy',
        category: 'Main Course',
        price: 360,
        image: '/hero-food.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'mc-004',
        name: 'Rasso',
        description: 'Signature spicy mutton curry, the heart of Saoji cuisine',
        category: 'Main Course',
        price: 450,
        image: '/hero-food.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'mc-005',
        name: 'Saoji Chicken Curry',
        description: 'Authentic chicken curry with traditional Saoji spices',
        category: 'Main Course',
        price: 350,
        image: '/hero-food.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'mc-006',
        name: 'Saoji Mutton Curry',
        description: 'Rich and spicy mutton curry, a Saoji classic',
        category: 'Main Course',
        price: 440,
        image: '/hero-food.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'mc-007',
        name: 'Saoji Paneer Masala',
        description: 'Cottage cheese in spicy Saoji gravy',
        category: 'Main Course',
        price: 280,
        image: '/hero-food.png',
        isVeg: true,
        spiceLevel: 2,
        available: true,
    },
    {
        id: 'mc-008',
        name: 'Saoji Veg Curry',
        description: 'Mixed vegetables in authentic Saoji masala',
        category: 'Main Course',
        price: 240,
        image: '/hero-food.png',
        isVeg: true,
        spiceLevel: 2,
        available: true,
    },
    {
        id: 'mc-009',
        name: 'Sara Wangi',
        description: 'Eggplant curry with Saoji spices',
        category: 'Main Course',
        price: 220,
        image: '/hero-food.png',
        isVeg: true,
        spiceLevel: 2,
        available: true,
    },

    // BIRYANIS (8 items)
    {
        id: 'br-001',
        name: 'Chicken Mutthi Kabab Biryani',
        description: 'Fragrant biryani with spicy chicken kababs',
        category: 'Biryanis',
        price: 380,
        image: '/biryani.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'br-002',
        name: 'Mini Chicken Biryani',
        description: 'Single serving of delicious chicken biryani',
        category: 'Biryanis',
        price: 220,
        image: '/biryani.png',
        isVeg: false,
        spiceLevel: 2,
        available: true,
    },
    {
        id: 'br-003',
        name: 'Mini Mutton Biryani',
        description: 'Single serving of tender mutton biryani',
        category: 'Biryanis',
        price: 260,
        image: '/biryani.png',
        isVeg: false,
        spiceLevel: 2,
        available: true,
    },
    {
        id: 'br-004',
        name: 'Mini Saoji Veg Biryani',
        description: 'Single serving vegetarian biryani with Saoji spices',
        category: 'Biryanis',
        price: 180,
        image: '/biryani.png',
        isVeg: true,
        spiceLevel: 2,
        available: true,
    },
    {
        id: 'br-005',
        name: 'Mutton Mutthi Kabab Biryani',
        description: 'Aromatic biryani with spicy mutton kababs',
        category: 'Biryanis',
        price: 420,
        image: '/biryani.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'br-006',
        name: 'Chicken Biryani – Saoji Style',
        description: 'Full portion of authentic Saoji chicken biryani',
        category: 'Biryanis',
        price: 400,
        image: '/biryani.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'br-007',
        name: 'Mutton Biryani – Saoji Style',
        description: 'Full portion of rich Saoji mutton biryani',
        category: 'Biryanis',
        price: 480,
        image: '/biryani.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'br-008',
        name: 'Veg Biryani – Saoji Style',
        description: 'Full portion vegetarian biryani with authentic spices',
        category: 'Biryanis',
        price: 320,
        image: '/biryani.png',
        isVeg: true,
        spiceLevel: 2,
        available: true,
    },

    // RICE & ROTI (4 items)
    {
        id: 'rr-001',
        name: 'Aedmi',
        description: 'Traditional Saoji bread',
        category: 'Rice & Roti',
        price: 40,
        image: '/thali.png',
        isVeg: true,
        spiceLevel: 1,
        available: true,
    },
    {
        id: 'rr-002',
        name: 'Bagara Rice',
        description: 'Aromatic rice with whole spices',
        category: 'Rice & Roti',
        price: 150,
        image: '/thali.png',
        isVeg: true,
        spiceLevel: 1,
        available: true,
    },
    {
        id: 'rr-003',
        name: 'Chapati',
        description: 'Soft whole wheat flatbread',
        category: 'Rice & Roti',
        price: 30,
        image: '/thali.png',
        isVeg: true,
        spiceLevel: 1,
        available: true,
    },
    {
        id: 'rr-004',
        name: 'Steamed Basmati Rice',
        description: 'Perfectly cooked basmati rice',
        category: 'Rice & Roti',
        price: 120,
        image: '/thali.png',
        isVeg: true,
        spiceLevel: 1,
        available: true,
    },

    // SAOJI THALIS (6 items)
    {
        id: 'th-001',
        name: 'Chicken Biryani Thali',
        description: 'Complete meal with chicken biryani, raita, and dessert',
        category: 'Saoji Thalis',
        price: 450,
        image: '/thali.png',
        isVeg: false,
        spiceLevel: 2,
        available: true,
    },
    {
        id: 'th-002',
        name: 'Mutton Biryani Thali',
        description: 'Complete meal with mutton biryani, raita, and dessert',
        category: 'Saoji Thalis',
        price: 520,
        image: '/thali.png',
        isVeg: false,
        spiceLevel: 2,
        available: true,
    },
    {
        id: 'th-003',
        name: 'Saoji Chicken Thali',
        description: 'Traditional thali with chicken curry, rice, roti, and sides',
        category: 'Saoji Thalis',
        price: 400,
        image: '/thali.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'th-004',
        name: 'Saoji Mutton Thali',
        description: 'Traditional thali with mutton curry, rice, roti, and sides',
        category: 'Saoji Thalis',
        price: 480,
        image: '/thali.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'th-005',
        name: 'Saoji Veg Thali',
        description: 'Complete vegetarian thali with curry, dal, rice, and roti',
        category: 'Saoji Thalis',
        price: 280,
        image: '/thali.png',
        isVeg: true,
        spiceLevel: 2,
        available: true,
    },
    {
        id: 'th-006',
        name: 'Veg Biryani Thali',
        description: 'Complete meal with veg biryani, raita, and dessert',
        category: 'Saoji Thalis',
        price: 360,
        image: '/thali.png',
        isVeg: true,
        spiceLevel: 2,
        available: true,
    },

    // RICE BOWLS (5 items)
    {
        id: 'rb-001',
        name: 'Chitko Rasso Bowl',
        description: 'Signature mutton rasso with rice in a bowl',
        category: 'Rice Bowls',
        price: 320,
        image: '/rice-bowl.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'rb-002',
        name: 'Dal Tadka Bowl',
        description: 'Comforting dal tadka with steamed rice',
        category: 'Rice Bowls',
        price: 180,
        image: '/rice-bowl.png',
        isVeg: true,
        spiceLevel: 1,
        available: true,
    },
    {
        id: 'rb-003',
        name: 'Saoji Chicken Bowl',
        description: 'Spicy chicken curry with rice, ready to eat',
        category: 'Rice Bowls',
        price: 260,
        image: '/rice-bowl.png',
        isVeg: false,
        spiceLevel: 3,
        available: true,
    },
    {
        id: 'rb-004',
        name: 'Saoji Paneer Bowl',
        description: 'Paneer masala with rice in a convenient bowl',
        category: 'Rice Bowls',
        price: 240,
        image: '/rice-bowl.png',
        isVeg: true,
        spiceLevel: 2,
        available: true,
    },
    {
        id: 'rb-005',
        name: 'Saoji Veg Bowl',
        description: 'Mixed veg curry with rice, perfect for a quick meal',
        category: 'Rice Bowls',
        price: 200,
        image: '/rice-bowl.png',
        isVeg: true,
        spiceLevel: 2,
        available: true,
    },

    // SWEETS (1 item)
    {
        id: 'sw-001',
        name: 'Gaajar Ka Halwa',
        description: 'Traditional carrot pudding with nuts and ghee',
        category: 'Sweets',
        price: 120,
        image: '/thali.png',
        isVeg: true,
        spiceLevel: 1,
        available: true,
    },
];

export const categories = [
    'All',
    'Starters',
    'Main Course',
    'Biryanis',
    'Rice & Roti',
    'Saoji Thalis',
    'Rice Bowls',
    'Sweets',
];
